# Generated by Django 4.2.10 on 2024-04-25 04:43

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('default_address', models.BooleanField(default=True)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=100)),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='CAT:', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Category_images')),
                ('desc', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Solved', 'Solved')], default='Initiated', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Invoice', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=20)),
                ('paid_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='PID:', unique=True)),
                ('title', models.CharField(default='Sample', max_length=100)),
                ('desc', models.CharField(default='lorem lroeam ipsm lorem doooi', max_length=500)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='Product_images')),
                ('in_stock', models.BooleanField(default=True)),
                ('featured_on_home_page', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default='4.99', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('in-review', 'In Review'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Multiple_Images/')),
            ],
            options={
                'verbose_name_plural': 'Product_Images',
            },
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default=None)),
                ('review', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='VEN:', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Vendor_images')),
                ('desc', models.CharField(blank=True, default='description for vendor', max_length=600, null=True)),
                ('address', models.CharField(default='ABC 2nd St Kdl Kollm Kerla Ind', max_length=500)),
                ('contact', models.CharField(default='+91 9999955555', max_length=20)),
                ('message_response_time', models.CharField(default='2 Days', max_length=10)),
                ('shipping_time', models.CharField(default='4 Days', max_length=10)),
                ('authentic_rating', models.CharField(default='100%', max_length=10)),
                ('return_days', models.CharField(default='7 Days', max_length=10)),
                ('warrenty_period', models.CharField(default='30 Days', max_length=10)),
            ],
        ),
    ]
