# Generated by Django 4.2.10 on 2024-04-03 15:46

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vendor', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='CAT:', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='PID:', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VID',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=15, prefix='VEN:', unique=True),
        ),
    ]
