# Generated by Django 4.2.10 on 2024-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_tags_alter_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='temporary',
            field=models.BooleanField(default=True),
        ),
    ]
