# Generated by Django 4.2.10 on 2024-04-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='temporary',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
