# Generated by Django 4.2.10 on 2024-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_cartorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
    ]
