# Generated by Django 4.2.10 on 2024-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Solved', 'Solved')], default='Initiated', max_length=20),
        ),
    ]
